// vue-project/src/views/Login.vue
<template>
  <div class="my-layout login">
    <div class="my-form login-form">
      <div class="input-group mb-3">
        <span class="input-group-text">@</span>
        <input
          v-model="userData.username"
          type="text"
          class="form-control"
          placeholder="Username"
          aria-label="Username"
          aria-describedby="basic-addon1"
        />
      </div>
      <div class="input-group mb-3">
        <span class="input-group-text">$</span>
        <input
          v-model="userData.password"
          type="password"
          class="form-control"
          placeholder="Password"
          aria-label="Username"
          aria-describedby="basic-addon1"
        />
      </div>
      <div class="panel">
        <button @click="login" type="button" class="btn btn-primary">
          Login
        </button>
      </div>
    </div>
  </div>
</template>

<script>
import axios from "axios";
import { useUserStore } from "@/stores/user";

export default {
  data() {
    return {
      userData: {},
    };
  },
  setup() {
    const storeUser = useUserStore();
    return {
      storeUser,
    };
  },
  methods: {
    async login() {
      const answer = await axios.post(
        "http://localhost:3001/api/auth/login",
        this.userData
      );
      console.log(answer);
      answer.data.ok ? alert(answer.data.msg2) : alert(!!!+answer.data.msg2);
      const authToken = answer.data.result.authToken;
      localStorage.setItem("authToken", authToken);
      await this.storeUser.getUserData();
      if (this.storeUser.user.username == "admin")
        this.$router.push("/admin/main");
      else this.$router.push("/");
    },
  },
};
</script>

<style>
@import '@/assets/base.css';
@media (min-width: 1024px) {
  .login {
  }

  .login-form {
    padding: 1rem;
    
  }

  .panel {
    text-align: center;
  }
}
</style>

// front/src/app/pages/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { ApiService } from 'src/app/services/api.service';
const log = console.log;

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.sass']
})
export class LoginComponent implements OnInit {
  userData = {
    password: '',
    username: '',
  }


  constructor(
    private api: ApiService
  ) { }

  ngOnInit(): void {
  }
  async login() {
    log(this.userData)
    const answer: any = await this.api.login(this.userData)
    log(answer)
    if (answer.ok) {
      localStorage.setItem('authToken', answer.result.authToken)
      alert('user was logged')
    } else {
      alert(answer.msg)
    }
  }

}

<div class="login">
    <div class="input-group mb-3">
        <span class="input-group-text">@</span>
        <input [(ngModel)]="userData.username" type="text" class="form-control" placeholder="Username" aria-label="Username"
            aria-describedby="basic-addon1">
    </div>
    <div class="input-group mb-3">
        <span class="input-group-text">$</span>
        <input [(ngModel)]="userData.password" type="password" class="form-control" placeholder="Password" aria-label="Username"
            aria-describedby="basic-addon1">
    </div>
    <div class="panel">
        <button (click)="login()" type="button" class="btn btn-primary">Login</button>
    </div>
</div>
