// front/src/views/public/Login.vue
<template>
  <div class="card my-layout login">
    <div class="card my-form login-form">
      <div class="input-group mb-3">
        <span class="input-group-text">@</span>
        <input
          v-model="userData.username"
          type="text"
          class="form-control"
          placeholder="Username"
          aria-label="Username"
          aria-describedby="basic-addon1"
        />
      </div>
      <div class="input-group mb-3">
        <span class="input-group-text">$</span>
        <input
          v-model="userData.password"
          type="password"
          class="form-control"
          placeholder="Password"
          aria-label="Username"
          aria-describedby="basic-addon1"
        />
      </div>
      <div class="panel">
        <button @click="storeUser.login(userData)" type="button" class="btn btn-primary">
          Login
        </button>
      </div>
    </div>
  </div>
</template>

<script>
import axios from "axios";
import { useUserStore } from "@/stores/user";

export default {
  data() {
    return {
      userData: {},
    };
  },
  setup() {
    const storeUser = useUserStore();
    return {
      storeUser,
    };
  },
  methods: {
    
  },
};
</script>

<style scoped>
@import '@/assets/base.css';

  .login-form {
    padding: 1rem;
    
  }

  .panel {
    text-align: center;
  }
</style>

// front/src/app/pages/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { ApiService } from 'src/app/services/api.service';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.sass']
})
export class LoginComponent implements OnInit {
  userData={
    password:'',
    username:'',
  }


  constructor(
    private api: ApiService
  ) { }

  ngOnInit(): void {
  }
  async login(){
    console.log(this.userData)
    const answer=await this.api.login(this.userData)
   console.log(answer)
  }

}

<div class="login">
    <div class="input-group mb-3">
        <span class="input-group-text">@</span>
        <input [(ngModel)]="userData.username" type="text" class="form-control" placeholder="Username" aria-label="Username"
            aria-describedby="basic-addon1">
    </div>
    <div class="input-group mb-3">
        <span class="input-group-text">$</span>
        <input [(ngModel)]="userData.password" type="password" class="form-control" placeholder="Password" aria-label="Username"
            aria-describedby="basic-addon1">
    </div>
    <div class="panel">
        <button (click)="login()" type="button" class="btn btn-primary">Login</button>
    </div>
</div>
